# -*- coding: utf-8 -*-
"""OntarioStats.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PnLUcFbETKYGlygBrHuhwEQR7QaDbchg
"""

import pandas as pd
import numpy as np
import seaborn as sns

ontarioStats = pd.read_csv('https://raw.githubusercontent.com/RenshiNX/UofTHacksAdroren/main/CovidStats.csv')
firstIndex = 459 - 90
rowsDelete = list(range(0, firstIndex))

ontarioRecentStats = ontarioStats.drop(ontarioStats.index[rowsDelete])
ontarioRecentCases = ontarioRecentStats[['Date', 'Recent cases']]
ontarioStats

sns.lineplot(data = ontarioRecentCases)